name: Design Build Ship
favicon: null
layout_spectrum: 0.19655
typography_spectrum: 0.69324
title: Design Build SHip
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7e7'
    - '#282826'
    - '#cac6bd'
    - '#f0ab5c'
    - '#7b6d63'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.3073920232709497
purpose: []
