name: Design Build Ship
favicon: null
layout_spectrum: 0.47212
typography_spectrum: 0.77608
title: Design Build Ship
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7e7'
    - '#282826'
    - '#cac6bd'
    - '#f0ab5c'
    - '#7b6d63'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
